INSERT INTO link_mappings (link_id, link_name, upstream_names, downstream_patterns, news_patterns, logic, direction_note, expected_relation) VALUES
('cu_al_manufacturing', '铜铝 → 电力设备/机器人/汽车零部件',
 ARRAY['铜连续','铝连续','伦铜','伦铝'],
 ARRAY['有色资源','金属新材料','电机','电网设备','电力设备','机器人','减速器','汽车零部件','汽车轻量化','家电'],
 ARRAY['铜','铝','机器人','电力设备','新能源车','汽车','家电','电机','线缆'],
 '铜铝在电机、线缆、连接器、车身和散热件中存在刚性用量；资源端与下游制造利润之间常存在成本和库存滞后。',
 '资源端可能同向受益，下游制造更关注成本转嫁和订单弹性。',
 'mixed'),
('black_chain', '黑色链 → 基建/机械/汽车/家电',
 ARRAY['螺纹钢连续','热轧卷板连续','铁矿石连续','焦煤连续'],
 ARRAY['煤炭','钢铁','工程机械','基建','地产链','汽车板材','家电','机械'],
 ARRAY['焦煤','煤炭','钢铁','螺纹','热卷','铁矿','基建','机械','家电','地产'],
 '煤焦钢价格影响钢厂利润和钢材价格，并进一步传导至工程机械、汽车板材、家电钣金等下游。',
 '上游走强可能交易煤炭/钢铁情绪，也可能压制下游制造利润。',
 'mixed'),
('soda_glass', '纯碱玻璃 → 光伏玻璃/玻璃基板/地产链',
 ARRAY['纯碱连续','玻璃连续'],
 ARRAY['玻璃行业','玻璃基板','光伏玻璃','光伏设备','建筑材料','地产链','装修建材'],
 ARRAY['纯碱','玻璃','玻璃基板','光伏玻璃','光伏','地产','建筑材料'],
 '纯碱提供玻璃成本边界，玻璃价格反映地产竣工、光伏玻璃和新型玻璃基板需求。',
 '原料下跌可能改善中游毛利；需求不足时成本下降未必转化为业绩。',
 'mixed'),
('oil_chemical', '原油化工 → 消费制造/包装/化纤/电子化学品',
 ARRAY['上海原油连续','纽约原油','甲醇连续'],
 ARRAY['石化','化工','煤化工','化纤','包装','电子化学品','消费制造','交运'],
 ARRAY['原油','油价','甲醇','化工','化纤','包装','石化','电子化学品'],
 '油价和甲醇通过化工品价格、物流费用、库存重估向中下游传导。',
 '通常滞后于商品价格，重点看价差、库存和下游提价能力。',
 'mixed'),
('rare_earth_motor', '稀土/磁材 → 电机/机器人/风电/新能源车',
 ARRAY['伦镍'],
 ARRAY['稀土永磁','小金属','电机','机器人','风电设备','新能源车','磁材'],
 ARRAY['稀土','磁材','永磁','电机','机器人','风电','新能源车'],
 '稀土磁材影响高性能电机，常与机器人、风电、新能源车形成题材和成本联动；当前以可得的有色/镍数据作弱代理，后续可补稀土价格源。',
 '缺少稀土现货时置信度需打折。',
 'same_direction'),
('gold_safe_haven', '黄金 → 贵金属/避险情绪',
 ARRAY['黄金'],
 ARRAY['贵金属','黄金概念','避险','军工'],
 ARRAY['黄金','贵金属','避险','地缘','美元','美债'],
 '黄金反映避险、实际利率和美元线索，可能传导至贵金属与防御性板块。',
 '更偏情绪与宏观传导，不一定体现产业利润链。',
 'same_direction')
ON CONFLICT (link_id) DO UPDATE SET
  link_name=EXCLUDED.link_name,
  upstream_names=EXCLUDED.upstream_names,
  downstream_patterns=EXCLUDED.downstream_patterns,
  news_patterns=EXCLUDED.news_patterns,
  logic=EXCLUDED.logic,
  direction_note=EXCLUDED.direction_note,
  expected_relation=EXCLUDED.expected_relation,
  updated_at=now();
